//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_WS.Camiones_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Camiones_VO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Camiones_VO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Id_CamionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_CamionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        private int CapacidadField;
        
        private double KilometrajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlFotoField;
        
        private bool DisponibilidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id_Camion {
            get {
                return this.Id_CamionField;
            }
            set {
                if ((this.Id_CamionField.Equals(value) != true)) {
                    this.Id_CamionField = value;
                    this.RaisePropertyChanged("Id_Camion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaField, value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Tipo_Camion {
            get {
                return this.Tipo_CamionField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_CamionField, value) != true)) {
                    this.Tipo_CamionField = value;
                    this.RaisePropertyChanged("Tipo_Camion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Capacidad {
            get {
                return this.CapacidadField;
            }
            set {
                if ((this.CapacidadField.Equals(value) != true)) {
                    this.CapacidadField = value;
                    this.RaisePropertyChanged("Capacidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double Kilometraje {
            get {
                return this.KilometrajeField;
            }
            set {
                if ((this.KilometrajeField.Equals(value) != true)) {
                    this.KilometrajeField = value;
                    this.RaisePropertyChanged("Kilometraje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string UrlFoto {
            get {
                return this.UrlFotoField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlFotoField, value) != true)) {
                    this.UrlFotoField = value;
                    this.RaisePropertyChanged("UrlFoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool Disponibilidad {
            get {
                return this.DisponibilidadField;
            }
            set {
                if ((this.DisponibilidadField.Equals(value) != true)) {
                    this.DisponibilidadField = value;
                    this.RaisePropertyChanged("Disponibilidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Camiones_Service.camiones_ServiceSoap")]
    public interface camiones_ServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCamiones", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cliente_WS.Camiones_Service.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cliente_WS.Camiones_Service.Camiones_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cliente_WS.Camiones_Service.Camiones_VO[]))]
        Cliente_WS.Camiones_Service.GetCamionesResponse GetCamiones(Cliente_WS.Camiones_Service.GetCamionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCamiones", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente_WS.Camiones_Service.GetCamionesResponse> GetCamionesAsync(Cliente_WS.Camiones_Service.GetCamionesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento camion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCamion", ReplyAction="*")]
        Cliente_WS.Camiones_Service.InsertarCamionResponse InsertarCamion(Cliente_WS.Camiones_Service.InsertarCamionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCamion", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente_WS.Camiones_Service.InsertarCamionResponse> InsertarCamionAsync(Cliente_WS.Camiones_Service.InsertarCamionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento camion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCamion", ReplyAction="*")]
        Cliente_WS.Camiones_Service.ActualizarCamionResponse ActualizarCamion(Cliente_WS.Camiones_Service.ActualizarCamionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCamion", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente_WS.Camiones_Service.ActualizarCamionResponse> ActualizarCamionAsync(Cliente_WS.Camiones_Service.ActualizarCamionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento EliminarCamionResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarCamion", ReplyAction="*")]
        Cliente_WS.Camiones_Service.EliminarCamionResponse EliminarCamion(Cliente_WS.Camiones_Service.EliminarCamionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarCamion", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente_WS.Camiones_Service.EliminarCamionResponse> EliminarCamionAsync(Cliente_WS.Camiones_Service.EliminarCamionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCamionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCamiones", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS.Camiones_Service.GetCamionesRequestBody Body;
        
        public GetCamionesRequest() {
        }
        
        public GetCamionesRequest(Cliente_WS.Camiones_Service.GetCamionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCamionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente_WS.Camiones_Service.ArrayOfAnyType parametros;
        
        public GetCamionesRequestBody() {
        }
        
        public GetCamionesRequestBody(Cliente_WS.Camiones_Service.ArrayOfAnyType parametros) {
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCamionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCamionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS.Camiones_Service.GetCamionesResponseBody Body;
        
        public GetCamionesResponse() {
        }
        
        public GetCamionesResponse(Cliente_WS.Camiones_Service.GetCamionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCamionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente_WS.Camiones_Service.Camiones_VO[] GetCamionesResult;
        
        public GetCamionesResponseBody() {
        }
        
        public GetCamionesResponseBody(Cliente_WS.Camiones_Service.Camiones_VO[] GetCamionesResult) {
            this.GetCamionesResult = GetCamionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarCamionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarCamion", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS.Camiones_Service.InsertarCamionRequestBody Body;
        
        public InsertarCamionRequest() {
        }
        
        public InsertarCamionRequest(Cliente_WS.Camiones_Service.InsertarCamionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarCamionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente_WS.Camiones_Service.Camiones_VO camion;
        
        public InsertarCamionRequestBody() {
        }
        
        public InsertarCamionRequestBody(Cliente_WS.Camiones_Service.Camiones_VO camion) {
            this.camion = camion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarCamionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarCamionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS.Camiones_Service.InsertarCamionResponseBody Body;
        
        public InsertarCamionResponse() {
        }
        
        public InsertarCamionResponse(Cliente_WS.Camiones_Service.InsertarCamionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarCamionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarCamionResult;
        
        public InsertarCamionResponseBody() {
        }
        
        public InsertarCamionResponseBody(string InsertarCamionResult) {
            this.InsertarCamionResult = InsertarCamionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarCamionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarCamion", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS.Camiones_Service.ActualizarCamionRequestBody Body;
        
        public ActualizarCamionRequest() {
        }
        
        public ActualizarCamionRequest(Cliente_WS.Camiones_Service.ActualizarCamionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarCamionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Cliente_WS.Camiones_Service.Camiones_VO camion;
        
        public ActualizarCamionRequestBody() {
        }
        
        public ActualizarCamionRequestBody(Cliente_WS.Camiones_Service.Camiones_VO camion) {
            this.camion = camion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarCamionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarCamionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS.Camiones_Service.ActualizarCamionResponseBody Body;
        
        public ActualizarCamionResponse() {
        }
        
        public ActualizarCamionResponse(Cliente_WS.Camiones_Service.ActualizarCamionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarCamionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ActualizarCamionResult;
        
        public ActualizarCamionResponseBody() {
        }
        
        public ActualizarCamionResponseBody(string ActualizarCamionResult) {
            this.ActualizarCamionResult = ActualizarCamionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarCamionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarCamion", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS.Camiones_Service.EliminarCamionRequestBody Body;
        
        public EliminarCamionRequest() {
        }
        
        public EliminarCamionRequest(Cliente_WS.Camiones_Service.EliminarCamionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarCamionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public EliminarCamionRequestBody() {
        }
        
        public EliminarCamionRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarCamionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarCamionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS.Camiones_Service.EliminarCamionResponseBody Body;
        
        public EliminarCamionResponse() {
        }
        
        public EliminarCamionResponse(Cliente_WS.Camiones_Service.EliminarCamionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarCamionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EliminarCamionResult;
        
        public EliminarCamionResponseBody() {
        }
        
        public EliminarCamionResponseBody(string EliminarCamionResult) {
            this.EliminarCamionResult = EliminarCamionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface camiones_ServiceSoapChannel : Cliente_WS.Camiones_Service.camiones_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class camiones_ServiceSoapClient : System.ServiceModel.ClientBase<Cliente_WS.Camiones_Service.camiones_ServiceSoap>, Cliente_WS.Camiones_Service.camiones_ServiceSoap {
        
        public camiones_ServiceSoapClient() {
        }
        
        public camiones_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public camiones_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public camiones_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public camiones_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente_WS.Camiones_Service.GetCamionesResponse Cliente_WS.Camiones_Service.camiones_ServiceSoap.GetCamiones(Cliente_WS.Camiones_Service.GetCamionesRequest request) {
            return base.Channel.GetCamiones(request);
        }
        
        public Cliente_WS.Camiones_Service.Camiones_VO[] GetCamiones(Cliente_WS.Camiones_Service.ArrayOfAnyType parametros) {
            Cliente_WS.Camiones_Service.GetCamionesRequest inValue = new Cliente_WS.Camiones_Service.GetCamionesRequest();
            inValue.Body = new Cliente_WS.Camiones_Service.GetCamionesRequestBody();
            inValue.Body.parametros = parametros;
            Cliente_WS.Camiones_Service.GetCamionesResponse retVal = ((Cliente_WS.Camiones_Service.camiones_ServiceSoap)(this)).GetCamiones(inValue);
            return retVal.Body.GetCamionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente_WS.Camiones_Service.GetCamionesResponse> Cliente_WS.Camiones_Service.camiones_ServiceSoap.GetCamionesAsync(Cliente_WS.Camiones_Service.GetCamionesRequest request) {
            return base.Channel.GetCamionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente_WS.Camiones_Service.GetCamionesResponse> GetCamionesAsync(Cliente_WS.Camiones_Service.ArrayOfAnyType parametros) {
            Cliente_WS.Camiones_Service.GetCamionesRequest inValue = new Cliente_WS.Camiones_Service.GetCamionesRequest();
            inValue.Body = new Cliente_WS.Camiones_Service.GetCamionesRequestBody();
            inValue.Body.parametros = parametros;
            return ((Cliente_WS.Camiones_Service.camiones_ServiceSoap)(this)).GetCamionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente_WS.Camiones_Service.InsertarCamionResponse Cliente_WS.Camiones_Service.camiones_ServiceSoap.InsertarCamion(Cliente_WS.Camiones_Service.InsertarCamionRequest request) {
            return base.Channel.InsertarCamion(request);
        }
        
        public string InsertarCamion(Cliente_WS.Camiones_Service.Camiones_VO camion) {
            Cliente_WS.Camiones_Service.InsertarCamionRequest inValue = new Cliente_WS.Camiones_Service.InsertarCamionRequest();
            inValue.Body = new Cliente_WS.Camiones_Service.InsertarCamionRequestBody();
            inValue.Body.camion = camion;
            Cliente_WS.Camiones_Service.InsertarCamionResponse retVal = ((Cliente_WS.Camiones_Service.camiones_ServiceSoap)(this)).InsertarCamion(inValue);
            return retVal.Body.InsertarCamionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente_WS.Camiones_Service.InsertarCamionResponse> Cliente_WS.Camiones_Service.camiones_ServiceSoap.InsertarCamionAsync(Cliente_WS.Camiones_Service.InsertarCamionRequest request) {
            return base.Channel.InsertarCamionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente_WS.Camiones_Service.InsertarCamionResponse> InsertarCamionAsync(Cliente_WS.Camiones_Service.Camiones_VO camion) {
            Cliente_WS.Camiones_Service.InsertarCamionRequest inValue = new Cliente_WS.Camiones_Service.InsertarCamionRequest();
            inValue.Body = new Cliente_WS.Camiones_Service.InsertarCamionRequestBody();
            inValue.Body.camion = camion;
            return ((Cliente_WS.Camiones_Service.camiones_ServiceSoap)(this)).InsertarCamionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente_WS.Camiones_Service.ActualizarCamionResponse Cliente_WS.Camiones_Service.camiones_ServiceSoap.ActualizarCamion(Cliente_WS.Camiones_Service.ActualizarCamionRequest request) {
            return base.Channel.ActualizarCamion(request);
        }
        
        public string ActualizarCamion(Cliente_WS.Camiones_Service.Camiones_VO camion) {
            Cliente_WS.Camiones_Service.ActualizarCamionRequest inValue = new Cliente_WS.Camiones_Service.ActualizarCamionRequest();
            inValue.Body = new Cliente_WS.Camiones_Service.ActualizarCamionRequestBody();
            inValue.Body.camion = camion;
            Cliente_WS.Camiones_Service.ActualizarCamionResponse retVal = ((Cliente_WS.Camiones_Service.camiones_ServiceSoap)(this)).ActualizarCamion(inValue);
            return retVal.Body.ActualizarCamionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente_WS.Camiones_Service.ActualizarCamionResponse> Cliente_WS.Camiones_Service.camiones_ServiceSoap.ActualizarCamionAsync(Cliente_WS.Camiones_Service.ActualizarCamionRequest request) {
            return base.Channel.ActualizarCamionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente_WS.Camiones_Service.ActualizarCamionResponse> ActualizarCamionAsync(Cliente_WS.Camiones_Service.Camiones_VO camion) {
            Cliente_WS.Camiones_Service.ActualizarCamionRequest inValue = new Cliente_WS.Camiones_Service.ActualizarCamionRequest();
            inValue.Body = new Cliente_WS.Camiones_Service.ActualizarCamionRequestBody();
            inValue.Body.camion = camion;
            return ((Cliente_WS.Camiones_Service.camiones_ServiceSoap)(this)).ActualizarCamionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente_WS.Camiones_Service.EliminarCamionResponse Cliente_WS.Camiones_Service.camiones_ServiceSoap.EliminarCamion(Cliente_WS.Camiones_Service.EliminarCamionRequest request) {
            return base.Channel.EliminarCamion(request);
        }
        
        public string EliminarCamion(int id) {
            Cliente_WS.Camiones_Service.EliminarCamionRequest inValue = new Cliente_WS.Camiones_Service.EliminarCamionRequest();
            inValue.Body = new Cliente_WS.Camiones_Service.EliminarCamionRequestBody();
            inValue.Body.id = id;
            Cliente_WS.Camiones_Service.EliminarCamionResponse retVal = ((Cliente_WS.Camiones_Service.camiones_ServiceSoap)(this)).EliminarCamion(inValue);
            return retVal.Body.EliminarCamionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente_WS.Camiones_Service.EliminarCamionResponse> Cliente_WS.Camiones_Service.camiones_ServiceSoap.EliminarCamionAsync(Cliente_WS.Camiones_Service.EliminarCamionRequest request) {
            return base.Channel.EliminarCamionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente_WS.Camiones_Service.EliminarCamionResponse> EliminarCamionAsync(int id) {
            Cliente_WS.Camiones_Service.EliminarCamionRequest inValue = new Cliente_WS.Camiones_Service.EliminarCamionRequest();
            inValue.Body = new Cliente_WS.Camiones_Service.EliminarCamionRequestBody();
            inValue.Body.id = id;
            return ((Cliente_WS.Camiones_Service.camiones_ServiceSoap)(this)).EliminarCamionAsync(inValue);
        }
    }
}
